image:
  repository: jammsen/palworld-dedicated-server
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  ## Example annotations for kube-vip or MetalLB to assign a specific IP to the LoadBalancer
  annotations: {}
    # kube-vip.io/loadbalancerIPs: 192.168.1.100
    # metallb.universe.tf/loadBalancerIPs: 192.168.1.100
  port: 8211

## Source RCON Protocol
rcon:
  ## Sets the RCON_ENABLED environment variable in the container
  enabled: true
  ## Sets the RCON_PORT environment variable in the container
  port: 25575
  ## Adds RCON_PORT to service to enable external access
  expose: false

resources:
  # limits:
  #   cpu: 4
  #   memory: 32Gi
  requests:
    cpu: 4
    memory: 16Gi

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: ""

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  ## Storage class of PV to bind. By default it looks for standard storage class.
  ## If the PV uses a different storage class, specify that here.
  # storageClass: ""
  accessMode: ReadWriteOnce
  size: 30Gi

  ## If subPath is set mount a sub folder of a volume instead of the root of the volume.
  ##
  subPath: ""

nodeSelector: {}

tolerations: []

affinity: {}

## Environment variables used to configure Palworld
## ref: https://github.com/jammsen/docker-palworld-dedicated-server/blob/develop/docs/ENV_VARS.md
## 
config:
  ## ConfigMap environment variables
  env:
    TZ: UTC                             # Timezone used for time stamping server backups
    ALWAYS_UPDATE_ON_START: true
    MULTITHREAD_ENABLED: true
    COMMUNITY_SERVER: false
    BACKUP_ENABLED: true
    BACKUP_CRON_EXPRESSION: "0 * * * *"  # Backup every hour
    BACKUP_RETENTION_POLICY: true        # Cleanup old backups
    BACKUP_RETENTION_AMOUNT_TO_KEEP: 168 # Retain backups for 7 days
    SERVER_SETTINGS_MODE: auto           # Apply game settings using environment variables
    SERVER_NAME: "Default Palworld Server"
    SERVER_DESCRIPTION: ""
    MAX_PLAYERS: 32
    PUBLIC_IP: ""
    PUBLIC_PORT: 8211

  ## Secret environment variables
  secretEnv:
    ## Should this Helm chart create the secret. If false, you must define the secret name.
    create: true
    ## The name of the secret
    name: ""
    ## Environment variables to add to the secret. Used when create = true.
    env:
      SERVER_PASSWORD: "serverPasswordHere"
      ADMIN_PASSWORD: "adminPasswordHere"

## Scrape metrics with palworld-exporter. Requires enabling RCON.
## ref: https://github.com/palworldlol/palworld-exporter/tree/main
##
metrics:
  enabled: false

  image:
    repository: docker.io/bostrt/palworld-exporter
    pullPolicy: Always
    tag: latest

  service:
    type: ClusterIP
    port: 9877
    # nodePort: ""
    annotations: {}

  serviceMonitor:
    ## Create Prometheus Operator ServiceMonitor resource
    enabled: false

    ## The namespace where the ServiceMonitor will be created (defaults to Release Namespace).
    namespace: ""

    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    interval: ""

    ## RelabelConfigs to apply to samples before scraping
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    relabelings: []

    ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    metricRelabelings: []

  ## Additional environment variables used to configure palworld-exporter
  ## ref: https://github.com/palworldlol/palworld-exporter/tree/main?tab=readme-ov-file#options
  ##
  env:
    ## Path to your Palworld save directory
    SAVE_DIRECTORY: /palworld/Pal/Saved
    LOG_LEVEL: INFO
    IGNORE_LOGGING_IN: false
